apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: kube-dns-v3
  namespace: default
  labels:
    k8s-app: kube-dns-v3
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v3
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v3
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        command:
        - /usr/local/bin/etcd
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.9
        args:
        # command = "/kube2sky"
        - -domain={{ salt['pillar.get']('kube_pods:skydns:dnsname') }}
        - -kubecfg_file=/etc/dns_token/kubeconfig
        - -kube_master_url=http://10.20.30.61:8080
        volumeMounts:
        - mountPath: /etc/dns_token
          name: dns-token
          readOnly: true
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        args:
        # command = "/skydns"
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain={{ salt['pillar.get']('kube_pods:skydns:dnsname') }}.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nslookup kubernetes.default.{{ salt['pillar.get']('kube_pods:skydns:dnsname') }} localhost >/dev/null
          initialDelaySeconds: 30
          timeoutSeconds: 5
      dnsPolicy: Default  # Don't use cluster DNS.
      volumes:
      - name: dns-token
        secret:
          secretName: token-system-dns
